server:
  port: 8081
  servlet:
    contextPath: /meli-mutants
  error:
    include-message: always

spring:
  application:
    name: "meli-mutants"
  webflux:
    base-path: /meli-mutants
  data:
    mongodb:
      database: application_database
      host: localhost
      port: 27017
      username: application_user
      password: application_pass
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
